test pre-commit script

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -1,10 +1,10 @@
-#!/bin/sh
-echo "Running git pre-commit hook"
-
-./gradlew lintKotlin
-
-STATUS=$?
-
-# return 1 exit code if running checks fails
-[ $RESULT -ne 0 ] && exit 1
+#!/bin/bash
+command="./gradlew lintKotlin"
+echo "Executing tests before commit"
+$command
+result=$?
+if [ "$result" -ne 0 ]; then
+ echo "Failed execution of tests"
+ exit 1
+fi
 exit 0
